pool:
  vmImage: 'windows-2019'

name: $(SourceBranchName)+1.$(Date:yyyy.MM)$(Rev:.r)

steps:
- script: echo Starting build pipeline!
  displayName: 'Hello from Albanian Xrm'

- powershell: |
    echo "##vso[task.setvariable variable=configuration;isOutput=true]release"
    echo "##vso[task.setvariable variable=BuildNumber;isOutput=true]$(($env:BuildNumber).Substring(($env:BuildNumber).LastIndexOf('+')+1))"
  name: MyVars
  env: 
    BRANCH: $(Build.SourceBranch)
    BuildNumber: $(Build.BuildNumber)
  displayName: 'Set Configuration Variable'

- task: SonarCloudPrepare@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  
  inputs:
    SonarCloud: 'AlbanianXrm SonarCloud'
    organization: 'albanian-xrm'
    scannerMode: 'MSBuild'
    projectKey: 'Albanian-Xrm_Customization-Manager'
    projectName: 'Customization-Manager'

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . dotnet-reportgenerator-globaltool
  displayName: Install ReportGenerator tool

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . coverlet.console
  displayName: Install Coverlet.Console tool

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.x' 
  displayName: 'Install NuGet 4.9.x'

- task: NuGetCommand@2
  displayName: 'Restoring NuGet packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: $(MyVars.configuration)
    msbuildArguments: '/p:Version=$(MyVars.BuildNumber)'
  displayName: 'Building Solution'

- task: VSTest@2
  displayName: 'Unit Tests'
  inputs:
    testAssemblyVer2: |
     **\*Tests.dll
     !**\obj\**
    codeCoverageEnabled: false
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
        Get-ChildItem src\*\bin\ -Include *Tests.dll -Recurse |
        Foreach-Object { 
            .\coverlet.exe $_.FullName --target "dotnet" --targetargs "vstest $($_.FullName) --logger:trx" --format "cobertura"
            $NewName = $_.Name + ".coverage.cobertura.xml"
            Rename-Item coverage.cobertura.xml $NewName
        }
  displayName: Generate Coverlet coverage report for test libraries

- script: |
    mkdir .\reports
    .\reportgenerator.exe -reports:*coverage.cobertura.xml -targetdir:reports -reporttypes:"HTMLInline;HTMLChart"
    dir .\reports
  displayName: Create coverage reports in html format to be displayed in AzureDevOps

- script: |
    mkdir .\reports
    .\reportgenerator.exe -reports:*coverage.cobertura.xml -targetdir:reports -reporttypes:"cobertura"
    dir .\reports
  displayName: Create coverage reports in xml format to be used for summary

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage to AzureDevOps'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(system.defaultworkingdirectory)\reports\Cobertura.xml'
    reportDirectory: '$(system.defaultworkingdirectory)\reports'

- task: SonarCloudAnalyze@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  

- task: SonarCloudPublish@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  
  inputs:
    pollingTimeoutSec: '300'

- task: NuGetCommand@2
  displayName: 'Creating NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)/NuGet'
    buildProperties: version=$(MyVars.BuildNumber)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  

- task: PublishBuildArtifacts@1
  displayName: 'Publishing NuGet package to pipeline'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/NuGet'
    artifactName: 'NuGet Package'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  

- powershell: Compress-Archive -Path src\AlbanianXrm.CustomizationManager.XrmToolBox\bin\Release\net462\XrmToolBox\Plugins\* -DestinationPath Plugins.zip
  displayName: 'Create zip for GitHub'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  

- task: PublishBuildArtifacts@1
  displayName: 'Publishing NuGet package to pipeline'
  inputs:
    pathtoPublish: 'Plugins.zip'
    artifactName: 'Plugin Package'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  