//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AlbanianXrm.CustomizationManager.Models
{
	
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("importjob")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.67")]
	public partial class ImportJob : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ImportJob() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "importjob";
		
		public const int EntityTypeCode = 9107;
		
		/// <summary>
		/// Unique identifier of the import job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importjobid")]
		public System.Nullable<System.Guid> ImportJobId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("importjobid");
			}
			set
			{
				this.SetAttributeValue("importjobid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importjobid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ImportJobId = value;
			}
		}
		
		/// <summary>
		/// Import Progress Percentage.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("progress")]
		public System.Nullable<double> Progress
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("progress");
			}
			set
			{
				this.SetAttributeValue("progress", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionname")]
		public string SolutionName
		{
			get
			{
				return this.GetAttributeValue<string>("solutionname");
			}
			set
			{
				this.SetAttributeValue("solutionname", value);
			}
		}
		
		public sealed class Fields
		{
			
			/// <summary>
			/// Unique identifier of the import job.
			/// </summary>
			public const string ImportJobId = "importjobid";
			
			public const string Id = "importjobid";
			
			/// <summary>
			/// Import Progress Percentage.
			/// </summary>
			public const string Progress = "progress";
			
			/// <summary>
			/// Unique identifier of the solution.
			/// </summary>
			public const string SolutionName = "solutionname";
		}
	}
	
	/// <summary>
	/// A solution which contains CRM customizations.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("solution")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.67")]
	public partial class Solution : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Solution() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "solution";
		
		public const int EntityTypeCode = 7100;
		
		/// <summary>
		/// User display name for the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("friendlyname")]
		public string FriendlyName
		{
			get
			{
				return this.GetAttributeValue<string>("friendlyname");
			}
			set
			{
				this.SetAttributeValue("friendlyname", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
			set
			{
				this.SetAttributeValue("solutionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.SolutionId = value;
			}
		}
		
		/// <summary>
		/// The unique name of this solution
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniquename")]
		public string UniqueName
		{
			get
			{
				return this.GetAttributeValue<string>("uniquename");
			}
			set
			{
				this.SetAttributeValue("uniquename", value);
			}
		}
		
		public sealed class Fields
		{
			
			/// <summary>
			/// User display name for the solution.
			/// </summary>
			public const string FriendlyName = "friendlyname";
			
			/// <summary>
			/// Unique identifier of the solution.
			/// </summary>
			public const string SolutionId = "solutionid";
			
			public const string Id = "solutionid";
			
			/// <summary>
			/// The unique name of this solution
			/// </summary>
			public const string UniqueName = "uniquename";
		}
	}
	
	/// <summary>
	/// A component of a CRM solution.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("solutioncomponent")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.67")]
	public partial class SolutionComponent : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public SolutionComponent() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "solutioncomponent";
		
		public const int EntityTypeCode = 7103;
		
		/// <summary>
		/// The object type code of the component.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componenttype")]
		public Microsoft.Xrm.Sdk.OptionSetValue ComponentType
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("componenttype");
			}
		}
		
		/// <summary>
		/// Indicates whether this component is metadata or data.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismetadata")]
		public System.Nullable<bool> IsMetadata
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismetadata");
			}
		}
		
		/// <summary>
		/// Unique identifier of the object with which the component is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		public System.Nullable<System.Guid> ObjectId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("objectid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the solution component.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutioncomponentid")]
		public System.Nullable<System.Guid> SolutionComponentId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutioncomponentid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutioncomponentid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				base.Id = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public Microsoft.Xrm.Sdk.EntityReference SolutionId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("solutionid");
			}
		}
		
		public sealed class Fields
		{
			
			/// <summary>
			/// The object type code of the component.
			/// </summary>
			public const string ComponentType = "componenttype";
			
			/// <summary>
			/// Indicates whether this component is metadata or data.
			/// </summary>
			public const string IsMetadata = "ismetadata";
			
			/// <summary>
			/// Unique identifier of the object with which the component is associated.
			/// </summary>
			public const string ObjectId = "objectid";
			
			/// <summary>
			/// Unique identifier of the solution component.
			/// </summary>
			public const string SolutionComponentId = "solutioncomponentid";
			
			public const string Id = "solutioncomponentid";
			
			/// <summary>
			/// Unique identifier of the solution.
			/// </summary>
			public const string SolutionId = "solutionid";
		}
		
		public sealed class OptionSets
		{
			
			public class IsMetadata
			{
				
				/// <summary>
				/// Data
				/// </summary>
				public const bool Data = false;
				
				/// <summary>
				/// Metadata
				/// </summary>
				public const bool Metadata = true;
			}
		}
	}
	
	public sealed class OptionSets
	{
		
		[System.Runtime.Serialization.DataContractAttribute()]
		[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.67")]
		public enum ComponentType
		{
			
			/// <summary>
			/// Entity
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Entity = 1,
			
			/// <summary>
			/// Attribute
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Attribute = 2,
			
			/// <summary>
			/// Relationship
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Relationship = 3,
			
			/// <summary>
			/// Attribute Picklist Value
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			AttributePicklistValue = 4,
			
			/// <summary>
			/// Attribute Lookup Value
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			AttributeLookupValue = 5,
			
			/// <summary>
			/// View Attribute
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ViewAttribute = 6,
			
			/// <summary>
			/// Localized Label
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			LocalizedLabel = 7,
			
			/// <summary>
			/// Relationship Extra Condition
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RelationshipExtraCondition = 8,
			
			/// <summary>
			/// Option Set
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			OptionSet = 9,
			
			/// <summary>
			/// Entity Relationship
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EntityRelationship = 10,
			
			/// <summary>
			/// Entity Relationship Role
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EntityRelationshipRole = 11,
			
			/// <summary>
			/// Entity Relationship Relationships
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EntityRelationshipRelationships = 12,
			
			/// <summary>
			/// Managed Property
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ManagedProperty = 13,
			
			/// <summary>
			/// Entity Key
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EntityKey = 14,
			
			/// <summary>
			/// Privilege
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Privilege = 16,
			
			/// <summary>
			/// PrivilegeObjectTypeCode
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			PrivilegeObjectTypeCode = 17,
			
			/// <summary>
			/// Role
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Role = 20,
			
			/// <summary>
			/// Role Privilege
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RolePrivilege = 21,
			
			/// <summary>
			/// Display String
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			DisplayString = 22,
			
			/// <summary>
			/// Display String Map
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			DisplayStringMap = 23,
			
			/// <summary>
			/// Form
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Form = 24,
			
			/// <summary>
			/// Organization
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Organization = 25,
			
			/// <summary>
			/// Saved Query
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SavedQuery = 26,
			
			/// <summary>
			/// Workflow
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Workflow = 29,
			
			/// <summary>
			/// Report
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Report = 31,
			
			/// <summary>
			/// Report Entity
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ReportEntity = 32,
			
			/// <summary>
			/// Report Category
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ReportCategory = 33,
			
			/// <summary>
			/// Report Visibility
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ReportVisibility = 34,
			
			/// <summary>
			/// Attachment
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Attachment = 35,
			
			/// <summary>
			/// Email Template
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EmailTemplate = 36,
			
			/// <summary>
			/// Contract Template
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ContractTemplate = 37,
			
			/// <summary>
			/// KB Article Template
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			KBArticleTemplate = 38,
			
			/// <summary>
			/// Mail Merge Template
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			MailMergeTemplate = 39,
			
			/// <summary>
			/// Duplicate Rule
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			DuplicateRule = 44,
			
			/// <summary>
			/// Duplicate Rule Condition
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			DuplicateRuleCondition = 45,
			
			/// <summary>
			/// Entity Map
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EntityMap = 46,
			
			/// <summary>
			/// Attribute Map
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			AttributeMap = 47,
			
			/// <summary>
			/// Ribbon Command
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RibbonCommand = 48,
			
			/// <summary>
			/// Ribbon Context Group
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RibbonContextGroup = 49,
			
			/// <summary>
			/// Ribbon Customization
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RibbonCustomization = 50,
			
			/// <summary>
			/// Ribbon Rule
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RibbonRule = 52,
			
			/// <summary>
			/// Ribbon Tab To Command Map
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RibbonTabToCommandMap = 53,
			
			/// <summary>
			/// Ribbon Diff
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RibbonDiff = 55,
			
			/// <summary>
			/// Saved Query Visualization
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SavedQueryVisualization = 59,
			
			/// <summary>
			/// System Form
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SystemForm = 60,
			
			/// <summary>
			/// Web Resource
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			WebResource = 61,
			
			/// <summary>
			/// Site Map
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SiteMap = 62,
			
			/// <summary>
			/// Connection Role
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ConnectionRole = 63,
			
			/// <summary>
			/// Complex Control
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ComplexControl = 64,
			
			/// <summary>
			/// Field Security Profile
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			FieldSecurityProfile = 70,
			
			/// <summary>
			/// Field Permission
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			FieldPermission = 71,
			
			/// <summary>
			/// Plugin Type
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			PluginType = 90,
			
			/// <summary>
			/// Plugin Assembly
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			PluginAssembly = 91,
			
			/// <summary>
			/// SDK Message Processing Step
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SDKMessageProcessingStep = 92,
			
			/// <summary>
			/// SDK Message Processing Step Image
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SDKMessageProcessingStepImage = 93,
			
			/// <summary>
			/// Service Endpoint
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ServiceEndpoint = 95,
			
			/// <summary>
			/// Routing Rule
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RoutingRule = 150,
			
			/// <summary>
			/// Routing Rule Item
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			RoutingRuleItem = 151,
			
			/// <summary>
			/// SLA
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SLA = 152,
			
			/// <summary>
			/// SLA Item
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SLAItem = 153,
			
			/// <summary>
			/// Convert Rule
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ConvertRule = 154,
			
			/// <summary>
			/// Convert Rule Item
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ConvertRuleItem = 155,
			
			/// <summary>
			/// Hierarchy Rule
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			HierarchyRule = 65,
			
			/// <summary>
			/// Mobile Offline Profile
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			MobileOfflineProfile = 161,
			
			/// <summary>
			/// Mobile Offline Profile Item
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			MobileOfflineProfileItem = 162,
			
			/// <summary>
			/// Similarity Rule
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SimilarityRule = 165,
			
			/// <summary>
			/// Custom Control
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			CustomControl = 66,
			
			/// <summary>
			/// Custom Control Default Config
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			CustomControlDefaultConfig = 68,
			
			/// <summary>
			/// Data Source Mapping
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			DataSourceMapping = 166,
			
			/// <summary>
			/// SDKMessage
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SDKMessage = 201,
			
			/// <summary>
			/// SDKMessageFilter
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SDKMessageFilter = 202,
			
			/// <summary>
			/// SdkMessagePair
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SdkMessagePair = 203,
			
			/// <summary>
			/// SdkMessageRequest
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SdkMessageRequest = 204,
			
			/// <summary>
			/// SdkMessageRequestField
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SdkMessageRequestField = 205,
			
			/// <summary>
			/// SdkMessageResponse
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SdkMessageResponse = 206,
			
			/// <summary>
			/// SdkMessageResponseField
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			SdkMessageResponseField = 207,
			
			/// <summary>
			/// WebWizard
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			WebWizard = 210,
			
			/// <summary>
			/// Index
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Index = 18,
			
			/// <summary>
			/// Import Map
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			ImportMap = 208,
			
			/// <summary>
			/// Canvas App
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			CanvasApp = 300,
			
			/// <summary>
			/// Connector
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Connector_371 = 371,
			
			/// <summary>
			/// Connector
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			Connector_372 = 372,
			
			/// <summary>
			/// Environment Variable Definition
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EnvironmentVariableDefinition = 380,
			
			/// <summary>
			/// Environment Variable Value
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EnvironmentVariableValue = 381,
			
			/// <summary>
			/// AI Project Type
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			AIProjectType = 400,
			
			/// <summary>
			/// AI Project
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			AIProject = 401,
			
			/// <summary>
			/// AI Configuration
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			AIConfiguration = 402,
			
			/// <summary>
			/// Entity Analytics Configuration
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EntityAnalyticsConfiguration = 430,
			
			/// <summary>
			/// Attribute Image Configuration
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			AttributeImageConfiguration = 431,
			
			/// <summary>
			/// Entity Image Configuration
			/// </summary>
			[System.Runtime.Serialization.EnumMemberAttribute()]
			EntityImageConfiguration = 432,
		}
	}
}
